//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_Api_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.CourseRegistrations = new HashSet<CourseRegistration>();
        }
    
        public int CourseId { get; set; }
        [RegularExpression("/^[a-zA-Z ]*$/")]
        public string CourseName { get; set; }
      [RegularExpression("[a-zA-Z]{2}[0-9]{4}")]
        public string CourseCode { get; set; }
        [Range(1, 16)]
        public int CourseHours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseRegistration> CourseRegistrations { get; set; }
    }
}
